---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nicoleliu
resources:
  - ../../base
  - virtual-service.yaml
patches:
  - path: patch-service-type.yaml
    target:
      kind: Service
      labelSelector: "app=project"
  - path: patch-deployment-project.yaml
    target:
      kind: Deployment
      labelSelector: "app=project"
